package processor;

import java.util.Set;

public class WordsInfo {
    public static final Set<String> POSITIVE = Set.of(
            "хороший", "отличный", "замечательный", "прекрасный", "великолепный",
            "потрясающий", "радостный", "счастливый",
            "милый", "добрый", "ласковый", "дружелюбный", "отзывчивый",
            "любимый", "красивый", "обаятельный", "привлекательный", "симпатичный",
            "вежливый", "честный", "искренний", "надежный", "решительный",
            "смелый", "умный", "талантливый", "творческий", "успешный",
            "сильный", "уверенный", "спокойный", "мудрый", "внимательный",
            "вдохновляющий", "поддерживающий", "позитивный", "оптимистичный", "яркий",
            "интересный", "крутой", "полезный", "важный", "значимый",
            "продуктивный", "находчивый", "целеустремлённый", "энергичный", "активный",
            "рад", "доволен", "люблю", "одобряю", "благодарный",
            "гармоничный", "сплочённый", "великодушный", "гостеприимный", "заботливый", "теплый", "уютный", "приветливый", "умиротворённый",
            "восхищённый", "ободряющий", "жизнерадостный", "бодрый", "живой",
            "лучший", "достойный", "светлый", "волшебный", "невероятный",
            "чудесный", "добродушный", "усердный", "трудолюбивый",
            "гениальный", "золотой", "лояльный",
            "осмысленный", "ясный", "приемлемый", "идеальный", "удачный",
            "усладный", "шикарный", "благополучный", "восхитительный", "изысканный",
            "радующий", "обнадеживающий", "бесподобный",

            "good", "great", "excellent", "amazing", "awesome",
            "wonderful", "fantastic", "brilliant", "incredible", "outstanding",
            "positive", "happy", "joyful", "cheerful", "delightful",
            "kind", "friendly", "supportive", "generous", "helpful",
            "lovely", "beautiful", "elegant", "graceful", "smart",
            "creative", "talented", "strong", "confident", "calm",
            "peaceful", "wise", "bright", "shining", "vibrant",
            "energetic", "successful", "motivating", "inspiring", "valuable",
            "precious", "honest", "loyal", "reliable", "trustworthy",
            "compassionate", "warm", "caring", "polite", "humble",
            "respectful", "brave", "fearless", "capable", "productive",
            "efficient", "magnificent", "glorious", "hopeful",
            "optimistic", "fantabulous", "splendid", "superb", "stellar",
            "remarkable", "notable", "noteworthy", "cool", "impressive",
            "exciting", "fresh", "refreshing", "pleasant",
            "positive-minded", "upbeat", "constructive", "ideal", "perfect",
            "winning", "favorable", "admirable", "praiseworthy", "noble",
            "charming", "appealing", "delicious", "enjoyable", "fun",
            "glad", "thankful", "appreciative", "worthy", "exceptional"
    );

    public static final Set<String> NEGATIVE = Set.of(
            "плохой", "ужасный", "отвратительный", "мерзкий", "кошмарный",
            "страшный", "тупой", "глупый", "злой", "агрессивный",
            "грубый", "надоедливый", "раздражающий", "некрасивый", "уродливый",
            "лживый", "фальшивый", "обманчивый", "опасный", "рискованный",
            "грустный", "печальный", "унылый", "подавленный", "несчастный",
            "токсичный", "вредный", "жестокий", "враждебный", "холодный",
            "неприятный", "некомфортный", "больной", "болезненный", "бесполезный",
            "бессмысленный", "разрушительный", "провальный", "негативный", "депрессивный",
            "завистливый", "эгоистичный", "жадный", "скупой",
            "грязный", "тёмный", "тоскливый", "обидный", "оскорбительный",
            "злопамятный", "подлый", "злобный", "трусливый",
            "неудачный", "ужасающе", "разочаровывающий", "подавляющий", "серый",
            "скучный", "тусклый", "безжизненный", "пассивный", "вялый",
            "гнилой", "отсталый", "ничтожный", "жалкий", "мизерный",
            "низкий", "противный", "неправильный", "ложный", "дикой",
            "слабый", "сломанный", "разбитый", "проблемный", "трудный",
            "скандальный", "некультурный", "бессовестный", "нечестный", "порочный",
            "захудалый", "грубоватый", "некачественный", "нелепый",
            "ошибочный", "худший", "мрачный", "тревожный", "разрушенный",

            "bad", "terrible", "awful", "horrible", "disgusting",
            "ugly", "rude", "mean", "toxic", "angry",
            "sad", "upset", "depressed", "annoying", "frustrating",
            "boring", "useless", "meaningless", "dangerous", "risky",
            "weak", "broken", "damaged", "fake", "liar",
            "dirty", "messy", "stressful", "painful", "fearful",
            "scary", "cruel", "violent", "hostile", "cold",
            "dark", "hopeless", "jealous", "selfish", "arrogant",
            "stupid", "foolish", "lazy", "unreliable", "dishonest",
            "corrupt", "offensive", "insulting", "bitter", "unpleasant",
            "annoyed", "ashamed", "pathetic", "miserable", "worthless",
            "inferior", "problematic", "harmful", "devastating", "chaotic",
            "sadistic", "manipulative", "toxic-minded", "negative", "weak-willed",
            "unhappy", "dreadful", "fearsome", "creepy", "gross",
            "repulsive", "nasty", "terrifying", "threatening", "unstable",
            "disappointing", "failing", "losing", "insecure", "dull",
            "lifeless", "troublesome", "unacceptable", "malicious",
            "damaging", "pointless", "insincere", "harsh", "unfair",
            "hurtful", "sorrowful", "tragic", "catastrophic"
    );
}
